### ISSUE TITLE
Support One-Click SQL Binding

### ISSUE THREAD

**Issue by breezewish** [pingcap/tidb-dashboard#781]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Now it is not easy to bind plans for a statement.

**Describe the feature you'd like:**

After https://github.com/pingcap/tidb/issues/18811 is implemented, the UI can be implemented in TiDB Dashboard that user can simply click a button to finish the plan binding.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by iosmanthus** [comment]
There are two proposals coming out of my head:

1. We could just add a single checkbox named `Stick on this plan` to `Execution Detail/Execution Plan`:
![image](https://user-images.githubusercontent.com/16307070/98525036-e6678880-22b2-11eb-9269-663941e94eaa.png). Users could just click this checkbox to bind to plan shown in the page.

2. Or we could show a checkbox list that contains the plan history including execution hints(execution time, etc) of the `SQL`. Users could select a plan that seems fast instead of try to find out which plan is the 'fast' one and try to rebind that plan.

**Comment by SabaPing** [comment]
Plan to release on v6.6.0.

**Comment by SabaPing** [comment]
Done by https://github.com/pingcap/tidb-dashboard/pull/1473.
