### ISSUE TITLE
cluster-info: disks showing host down message for tidb

### ISSUE THREAD

**Issue by dveeden** [pingcap/tidb-dashboard#926]
## Bug Report

**What did you do?**

Deploy TiDB with the TiDB Operator on AWS EKS. Then use the dashboard.

**What did you expect to see?**

Disk info for all node types

**What did you see instead?**

"Host information is unavailable due to nstances on the host is down"

![image](https://user-images.githubusercontent.com/1272980/118247900-0109fc80-b4a4-11eb-9357-fb400a2462b8.png)

In the debugger it does show partitions. So the host is not down.

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

The top left corner shows "PD v5.0.1"

**Comment by breeswish** [comment]
@baurine Would you like to take a look?

**Comment by baurine** [comment]
sorry for just seeing this issue, let me have a look.

**Comment by baurine** [comment]
hi @dveeden sorry for the late reply, recently I am handling a similar issue.

For this case, according to the console information and code logic, it is because there is no matched `partitions.path` and `instances.partition_path_lower`, it is expected that it has at least one pair that their values are the same.

![image](https://user-images.githubusercontent.com/1284531/122712893-59989a80-d297-11eb-82f5-4138de7e5487.png)

I will investigate why this happens. Would you like to collect some information for us if the environment is still there?

Connect the database, run below 2 SQL:

```sql
select * from INFORMATION_SCHEMA.CLUSTER_LOAD where TYPE='tidb';
select * from INFORMATION_SCHEMA.CLUSTER_HARDWARE where TYPE='tidb';
```

> Deploy TiDB with the TiDB Operator on AWS EKS.

What are the detailed steps? Maybe we can try to reproduce it. 

Thanks!

**Comment by xpepermint** [comment]
I see the same error message. I deployed a minimum cluster following this: https://docs.pingcap.com/tidb-in-kubernetes/stable/get-started.

<img width="1212" alt="Screenshot 2021-08-28 at 17 07 58" src="https://user-images.githubusercontent.com/174279/131222554-a3d6c516-166b-48de-a09a-32ab0820ca33.png">

**Comment by baurine** [comment]
> @baurine I see the same error message. I deployed a minimum cluster following this: https://docs.pingcap.com/tidb-in-kubernetes/stable/get-started.
> 
> <img alt="Screenshot 2021-08-28 at 17 07 58" width="1212" src="https://user-images.githubusercontent.com/174279/131222554-a3d6c516-166b-48de-a09a-32ab0820ca33.png">

hi @xpepermint , yep, I found the root cause, it is because when we deploy in the cloud, we don't pass the `-log-file` command parameter to tidb-server, it sounds weird but it is true, the current implementation of disk info depends on this parameter, when this value is empty, something goes wrong. Because this info can be got from grafana, it's not that urgent to fix, but we plan to refactor it.

**Comment by xpepermint** [comment]
Good. I'm happy to see that you've found the bug. Is there a chance to get it to a `Milestone`?

**Comment by baurine** [comment]
> Good. I'm happy to see that you've found the bug. Is there a chance to get it to a `Milestone`?

We haven't decided yet.

**Comment by breeswish** [comment]
Sounds like this needs some change in TiDB Operator? @baurine

**Comment by baurine** [comment]
I am just curious that why disk info needs to depend on the `--log-file` parameter, can we remove this dependency.

**Comment by breeswish** [comment]
> I am just curious that why disk info needs to depend on the `--log-file` parameter, can we remove this dependency? 

@baurine I guess it is because the disk info contains info for ALL disks, while we only want to display one in this case.

**Comment by breeswish** [comment]
Do we have further updates? @baurine

**Comment by baurine** [comment]
> Do we have further updates? @baurine

nope, maybe we can arrange a task for this issue in the next sprint.

**Comment by dveeden** [comment]
@baurine @breezewish any updates?

**Comment by dveeden** [comment]
![image](https://user-images.githubusercontent.com/1272980/173604079-e5c0b697-c4ce-4454-ac91-7da0bb39bfb5.png)
This is with v6.1.0 and it shows the wrong mountpoint for TiFlash when running with `tiup playground`

**Comment by baurine** [comment]
hi @dveeden , I will try to resolve it in the next release. 

/cc @lilyjazz

**Comment by baurine** [comment]
As discussed with PM, we decide to update the wrong tooltip first by PR #1469 .
