### ISSUE TITLE
cluster-info: node startup time display incorrect week

### ISSUE THREAD

**Issue by pcqz** [pingcap/tidb-dashboard#936]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

https://asktug.com/t/topic/93619

**What did you do?**

Start cluster on Wednesday this week.

**What did you expect to see?**
Today is Friday,  startup time should display this Wednesday.

**What did you see instead?**
![image](https://user-images.githubusercontent.com/45614653/121661476-cf05ad80-cad6-11eb-8cc9-4dd2358a3eea.png)

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**
v5.0.2

**Comment by breeswish** [comment]
Thanks for the report! /cc @baurine @shhdgit PTAL

**Comment by unbyte** [comment]
This is the difference between Chinese and English.

In English, `last` means *the most recent in time; latest*. `Last Wednesday` means the most recent Wednesday, which in this case is the Wednesday in this week. And that's how dayjs, a package used in dashboard, handle calendar data.

I think it's more like a problem caused by the translation ignoring the fact that the differences between Chinese and English.

**Comment by shhdgit** [comment]
It looks like we have a similar problem at [dayjs#1226](https://github.com/iamkun/dayjs/issues/1226), and need the `sameWeek`.

**Comment by breeswish** [comment]
So how can we fix it? How about utilizing the dayjs token override feature?
